#include "../include/IrGenerator.h"

// == HELPERS ==
void casmlang::IrGenerator::load_ast(std::unique_ptr<ScopeBlock> ast) {
    entry_point = std::move(ast);
}
std::vector<std::unique_ptr<casmlang::Ir>> casmlang::IrGenerator::give_ir() {
    return std::move(ir);
}

void casmlang::IrGenerator::generate_ir() {
    entry_point->accept(*this);
}
void casmlang::IrGenerator::print_ir(std::ostream& stream) {
    for (auto& irnode : ir) {
        irnode->print(stream);
        stream << "\n";
    }
}
std::string casmlang::IrGenerator::generateLabel() {
    return "autogeneratedLabel__casmLang" +
           std::to_string(
               labelCounter++); // weird name to decrease collision with user-defined labels
}

// == VISIT ==
void casmlang::IrGenerator::visit(ScopeBlock& node) {
    for (auto& child : node.children) {
        child->accept(*this);
    }
};
void casmlang::IrGenerator::visit(StringLiteral& node) {

};
void casmlang::IrGenerator::visit(FloatLiteral& node) {};
void casmlang::IrGenerator::visit(IntegerLiteral& node) {
    currentNode = std::make_unique<IrIntLit>(node.number);
};
void casmlang::IrGenerator::visit(BooleanLiteral& node) {};
void casmlang::IrGenerator::visit(VoidLiteral& node) {};
void casmlang::IrGenerator::visit(VariableDefinition& node) {
    node.value->accept(*this);
    std::unique_ptr<casmlang::IrExpr> expression = get_current_as<casmlang::IrExpr>();
    ir.push_back(std::make_unique<IrMovStmt>(node.memory, std::move(expression)));
};
void casmlang::IrGenerator::visit(BinaryExpression& node) {};
void casmlang::IrGenerator::visit(RoutineCallExpr& node) {};
void casmlang::IrGenerator::visit(VariableReference& node) {};
void casmlang::IrGenerator::visit(UnaryExpression& node) {};
void casmlang::IrGenerator::visit(VariableReassignment& node) {
    node.value->accept(*this);
    std::unique_ptr<casmlang::IrExpr> expression = get_current_as<casmlang::IrExpr>();
    ir.push_back(std::make_unique<IrMovStmt>(node.memory, std::move(expression)));
};
void casmlang::IrGenerator::visit(RoutineCallStmt& node) {
    ir.push_back(std::make_unique<IrRtnCall>(node.identifier));
};
void casmlang::IrGenerator::visit(RoutineDefinition& node) {
    ir.push_back(std::make_unique<IrLabelStmt>(node.identifier));
    node.scope->accept(*this);
    if (node.hasRet)
        ir.push_back(std::make_unique<IrRetStmt>());
};
void casmlang::IrGenerator::visit(SectionDefinition& node) {
    ir.push_back(std::make_unique<IrSection>(node.identifier));
    node.scope->accept(*this);
}
void casmlang::IrGenerator::visit(Global& node) {
    ir.push_back(std::make_unique<IrGlobal>(node.identifier));
}
void casmlang::IrGenerator::visit(RoutineDeclaration& node) {}
void casmlang::IrGenerator::visit(AsmInstruction& node) {
    ir.push_back(std::make_unique<IrAsm>(node.instruction));
}
void casmlang::IrGenerator::visit(DeleteSymbol& node) {}
void casmlang::IrGenerator::visit(FreeMemory& node) {}
void casmlang::IrGenerator::visit(IfStatement& node) {
    std::string jumpName = condMap.at(node.cond);
    std::string trueLabel = generateLabel();
    std::string endLabel = generateLabel();

    ir.push_back(std::make_unique<IrJmp>(trueLabel, jumpName));
    ir.push_back(std::make_unique<IrJmp>(endLabel));
    ir.push_back(std::make_unique<IrLabelStmt>(trueLabel));
    node.scope->accept(*this);
    ir.push_back(std::make_unique<IrLabelStmt>(endLabel));
};
