#include "../include/IrPrinter.h"

namespace casmlang {
void IrPrinter::print_indent(std::ostream& stream) {
    for (int i = 0; i < indent; i++) {
        stream << "    ";
    }
}
void IrPrinter::dispatch_print(Ir* instr, std::ostream& stream) {
    if (!instr)
        panic("Internal, cannot choose print dispatcher for instruction 0x00");

    if (auto cst = dynamic_cast<IrMovStmt*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrLabelStmt*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrRetStmt*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrRtnCall*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrGlobal*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrIntLit*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrSection*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrAsm*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrJmp*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrCmp*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrMemName*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrSyscall*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrAdd*>(instr))
        instr_print(cst, stream);
    else if (auto cst = dynamic_cast<IrSub*>(instr))
        instr_print(cst, stream);
    else
        panic("Internal, invalid print dispatch for instruction");
}

void IrPrinter::instr_print(IrMovStmt* ins, std::ostream& stream) {
    print_indent(stream);
    stream << "mov ";
    stream << ins->memname;
    stream << ", ";
    dispatch_print(ins->value.get(), stream);
}
void IrPrinter::instr_print(IrLabelStmt* ins, std::ostream& stream) {
    stream << ins->labeltext << ":";
}
void IrPrinter::instr_print(IrRetStmt* ins, std::ostream& stream) {
    print_indent(stream);
    stream << "ret";
    indent--;
}
void IrPrinter::instr_print(IrRtnCall* ins, std::ostream& stream) {
    print_indent(stream);
    stream << "call " << ins->rtnname;
    indent--;
}
void IrPrinter::instr_print(IrGlobal* ins, std::ostream& stream) {
    print_indent(stream);
    stream << "global " << ins->identifier;
}
void IrPrinter::instr_print(IrSection* ins, std::ostream& stream) {
    indent = 0;
    stream << "section ." << ins->text;
    indent++;
}
void IrPrinter::instr_print(IrAsm* ins, std::ostream& stream) {
    print_indent(stream);
    stream << ins->instruction << " ; direct conversion";
}
void IrPrinter::instr_print(IrJmp* ins, std::ostream& stream) {
    print_indent(stream);
    stream << ins->name << " " << ins->location;
}
void IrPrinter::instr_print(IrCmp* ins, std::ostream& stream) {
    print_indent(stream);
    stream << "cmp " << ins->left << ", " << ins->right;
}
void IrPrinter::instr_print(IrSyscall* ins, std::ostream& stream) {
    print_indent(stream);
    stream << "syscall";
}
void IrPrinter::instr_print(IrAdd* ins, std::ostream& stream) {
    print_indent(stream);
    stream << "add ";
    dispatch_print(ins->destination.get(), stream); // NASM uses Intel syntax, so `add dest, src`
    stream << ", ";
    dispatch_print(ins->source.get(), stream);
}
void IrPrinter::instr_print(IrSub* ins, std::ostream& stream) {
    print_indent(stream);
    stream << "sub ";
    dispatch_print(ins->destination.get(), stream); // NASM uses Intel syntax, so `sub dest, src`
    stream << ", ";
    dispatch_print(ins->source.get(), stream);
}

void IrPrinter::instr_print(IrIntLit* ins, std::ostream& stream) {
    stream << ins->number;
}
void IrPrinter::instr_print(IrMemName* ins, std::ostream& stream) {
    stream << ins->name;
}

void IrPrinter::load_ir(std::vector<std::unique_ptr<Ir>> ir_) {
    ir = std::move(ir_);
}
void IrPrinter::print(std::ostream& stream) {
    stream << "; this is an autogenerated assembly file\n";
    stream << "; it is not designed to be human readable. if possible, read the .casm file that "
              "generated it.\n";
    stream << "; == generated via CasmLang == https://www.github.com/Mher-DeLight/CasmLang ==\n";
    for (auto& instr : ir) {
        dispatch_print(instr.get(), stream);
        stream << "\n";
    }
}
} // namespace casmlang